export const filterOptions = {
  type: [
    { value: 'all', label: 'All Types' },
    { value: 'hardware', label: 'Hardware' },
    { value: 'software', label: 'Software' },
    { value: 'services', label: 'Services' },
  ],
  sort: [
    { value: 'none', label: 'None' },
    { value: 'asc', label: 'A to Z' },
    { value: 'desc', label: 'Z to A' },
  ],
};

export const forecastColumns = [
  'Sl. No.',
  'Division name',
  'Item',
  'Item Descriptions',
  'QTY',
  'Existing Stock',
  'Previous Procurement date of similar Item',
  'Estimated cost each',
  'Cash Outgo (2026-27)',
  'Whether Common TDCC Possible',
  'Possibility of using the same items for other project',
  'Necessary of using hardware technologies',
  'Initiation of condemnation of store',
  'Remarks',
  'Action',
];

export const forecastRows = [
  {
    id: 1,
    division: 'Anderson Group',
    item: 'Seismic Sensors',
    description: '7 & 8',
    qty: 7,
    existingStock: 2,
    previousProcurement: '10/02/2024',
    estimatedCost: '23,60,000',
    cashOutgo: '23,20,000.00',
    commonTdcc: 'Yes',
    crossProjectUse: 'Yes',
    hardwareNeed: 'Yes',
    condemnation: 'Yes',
    remarks: 'Requires immediate action',
  },
  {
    id: 2,
    division: 'Orion Systems',
    item: 'Cryogenic Coolers',
    description: '12',
    qty: 12,
    existingStock: 6,
    previousProcurement: '22/11/2023',
    estimatedCost: '6,80,000',
    cashOutgo: '6,20,000.00',
    commonTdcc: 'No',
    crossProjectUse: 'Yes',
    hardwareNeed: 'Yes',
    condemnation: 'No',
    remarks: 'Ready for distribution',
  },
  {
    id: 3,
    division: 'Vector Works',
    item: 'Optimum Tracking',
    description: '6',
    qty: 6,
    existingStock: 1,
    previousProcurement: '08/07/2023',
    estimatedCost: '12,60,000',
    cashOutgo: '12,10,000.00',
    commonTdcc: 'Yes',
    crossProjectUse: 'No',
    hardwareNeed: 'Yes',
    condemnation: 'No',
    remarks: 'Awaiting final approval',
  },
  {
    id: 4,
    division: 'Optimus Dynamics',
    item: 'Alphine Guidance Systems',
    description: '5',
    qty: 5,
    existingStock: 4,
    previousProcurement: '19/05/2022',
    estimatedCost: '9,00,000',
    cashOutgo: '8,60,000.00',
    commonTdcc: 'No',
    crossProjectUse: 'Yes',
    hardwareNeed: 'Yes',
    condemnation: 'No',
    remarks: 'Successfully delivered',
  },
  {
    id: 5,
    division: 'Airwave Labs',
    item: 'Vanguard Aerospace',
    description: '9 & 12',
    qty: 9,
    existingStock: 3,
    previousProcurement: '05/12/2021',
    estimatedCost: '15,60,000',
    cashOutgo: '15,20,000.00',
    commonTdcc: 'Yes',
    crossProjectUse: 'Yes',
    hardwareNeed: 'Yes',
    condemnation: 'Yes',
    remarks: 'Needs further evaluation',
  },
  {
    id: 6,
    division: 'Stellar Works',
    item: 'Optimum Tracking',
    description: '6',
    qty: 6,
    existingStock: 1,
    previousProcurement: '16/03/2021',
    estimatedCost: '4,56,000',
    cashOutgo: '4,20,000.00',
    commonTdcc: 'No',
    crossProjectUse: 'No',
    hardwareNeed: 'Yes',
    condemnation: 'No',
    remarks: 'Temporarily suspended',
  },
];

export const modalFields = [
  { label: 'Enter Forecast year', type: 'date', key: 'forecastYear', fullWidth: true },
  { label: 'Enter Division Name', placeholder: 'Enter', key: 'divisionName' },
  { label: 'Descriptions', placeholder: 'Enter', key: 'descriptions' },
  { label: 'Enter Item', placeholder: 'Enter', key: 'item' },
  { label: 'QTY', placeholder: 'Enter', key: 'qty' },
  { label: 'Previous Procurement date of similar Item', type: 'date', key: 'previousDate' },
  { label: 'Estimated cost each (in Lac)', placeholder: 'Enter amount', key: 'estimatedCost' },
  { label: 'Demand Indication Months', placeholder: 'Enter Number', key: 'demandMonths' },
  { label: 'Build or Project/Misc', placeholder: 'Enter Name', key: 'buildProject' },
  { label: 'DPP 2020 S No.', placeholder: 'Enter Number', key: 'dppNumber' },
  { label: 'Likely amount of cash Outgo Rs', placeholder: 'Enter Number', key: 'cashOutgo' },
  { label: 'Cash Outgo split over 2026-27', placeholder: 'Enter', key: 'cashSplit' },
  { label: 'Existing Stock', placeholder: 'Enter Number', key: 'existingStock' },
  { label: 'Whether Common TDCC Possible', placeholder: 'Enter Yes/ No', key: 'commonTdcc' },
  { label: 'Possibility of using the same items for other project', placeholder: 'Enter Yes/ No', key: 'crossProjectUse' },
  { label: 'Necessary of using hardware technologies', placeholder: 'Enter Yes/ No', key: 'hardwareNeed' },
  { label: 'Initiation of condemnation of store', placeholder: 'Enter Yes/ No', key: 'condemnation' },
  { label: 'Remarks', placeholder: 'Enter remarks', key: 'remarks', multiline: true },
];
